### ISSUE TITLE
Get Course Info

### ISSUE THREAD

**Issue by eileenrob84** [ywCN/StudentAssistant#5]
1.	Title: Get Course Info
2.	Priority: High
3.	Estimate: 21
4.	Requirement: As a student, I want to obtain course information (including course description, time schedule, listed professor and other relevant data) for available courses so that I can make an informed decision on whether to add the course or not.

**Comment by ywCN** [comment]
TODO: Save panda tables into a text. Parse info in the text files and save them into text file or database.

**Comment by ywCN** [comment]
Enter course ID, returns all info.

**Comment by ywCN** [comment]
Available Information: SectionTitle, CallNumber, StatusSeatsAvailable, DaysTimeLocation, Instructor, SessionAndDates, Credits

**Comment by ywCN** [comment]
Got them.
TODO: save info into database. Then write a new program for user to search information in the database.

**Comment by ywCN** [comment]
Finished.

**Comment by ywCN** [comment]
[https://github.com/ywCN/StudentAssistant/blob/master/user_search_course.py](url)

**Comment by eileenrob84** [comment]
Youhao,

I think (just my opinion) we need to demo this to Prof. Rowland before we
can close the issue. But we should talk about this with the rest of the
team to decide on our plan. Please help me remember to bring this up after
we give our status to Prof Rowland Tues. night.  I think we forgot to
discuss this when we were writing the development plan.

Thanks

Eileen
